declare variable $URI as xs:string external;
declare variable $URIS_BATCH_REF as xs:string external;
declare variable $foo as xs:string external;

"This is a file generated by the XQUERY-MODULE (Transform) which typically contains a report.  This information [" || $URI || "] was passed from the Selector."